game:
  duration: 180
  countdown: 5
points:
  DIAMOND_ORE: 10
  EMERALD_ORE: 8
  GOLD_ORE: 6
  IRON_ORE: 4
  COAL_ORE: 2
  REDSTONE_ORE: 3
  LAPIS_ORE: 3
arenas:
  default:
    world: world
    x: 0.0
    y: 64.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0
